import type { Metadata } from "next";
import { MainLayout } from "./ui/MainLayout";

import "@stellar/design-system/build/styles.min.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div id="root">
          <MainLayout>{children}</MainLayout>
        </div>
      </body>
    </html>
  );
}
